---
plugin: yc_compute
folders:
  - b1gbvus817uonomhjj9o
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: ../../key.json
hostnames:
  - fqdn
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address

groups:
  db: labels['tags'] == 'reddit-db'
  app: labels['tags'] == 'reddit-app'
