---
- name: Install MongoDB 4.4
  hosts: all
  become: true

  tasks:
  - name: Add APT key
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.4.asc
      state: present

  - name: Add APT repository
    apt_repository:
      repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.4 multiverse
      state: present

  - name: Install mongodb package
    apt:
      name: mongodb-org
      state: present

  - name: Configure service supervisor
    systemd:
      name: mongod
      enabled: yes
