---
- name: Wait unlock /var/lib/dpkg/lock-frontend
  shell: while PID=$(pidof -s apt-get); do tail --pid=$PID -f /dev/null; done
  changed_when: false
  tags: ruby

- name: Install ruby and rubygems and required packages
  apt:
    name:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
    update_cache: yes
    autoclean: yes
  tags: ruby
